%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-joy-teleop
Version:        1.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS joy_teleop package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-galactic-control-msgs
Requires:       ros-galactic-rclpy
Requires:       ros-galactic-rosidl-runtime-py
Requires:       ros-galactic-sensor-msgs
Requires:       ros-galactic-teleop-tools-msgs
Requires:       ros-galactic-trajectory-msgs
Requires:       ros-galactic-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-galactic-action-tutorials-interfaces
BuildRequires:  ros-galactic-ament-copyright
BuildRequires:  ros-galactic-ament-flake8
BuildRequires:  ros-galactic-ament-pep257
BuildRequires:  ros-galactic-ament-xmllint
BuildRequires:  ros-galactic-example-interfaces
BuildRequires:  ros-galactic-geometry-msgs
BuildRequires:  ros-galactic-launch-ros
BuildRequires:  ros-galactic-launch-testing
BuildRequires:  ros-galactic-std-msgs
BuildRequires:  ros-galactic-std-srvs
BuildRequires:  ros-galactic-test-msgs
%endif

%description
A (to be) generic joystick interface to control a robot

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/galactic"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Wed Nov 23 2022 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.3.0-1
- Autogenerated by Bloom

* Tue Apr 20 2021 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.2.1-2
- Autogenerated by Bloom

* Fri Mar 26 2021 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.2.1-1
- Autogenerated by Bloom

