%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-joy-teleop
Version:        1.8.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS joy_teleop package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-control-msgs
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-rosidl-runtime-py
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-teleop-tools-msgs
Requires:       ros-kilted-trajectory-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
BuildRequires:  ros-kilted-ament-xmllint
BuildRequires:  ros-kilted-example-interfaces
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-launch-ros
BuildRequires:  ros-kilted-launch-testing
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-test-msgs
%endif

%description
A (to be) generic joystick interface to control a robot

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Wed Apr 23 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.8.0-2
- Autogenerated by Bloom

* Thu Apr 17 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.8.0-1
- Autogenerated by Bloom

* Wed Nov 06 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.7.0-1
- Autogenerated by Bloom

* Tue Oct 01 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.6.0-1
- Autogenerated by Bloom

* Mon Sep 02 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.5.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 1.5.0-2
- Autogenerated by Bloom

